<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Article extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Article_model');
    } 

    /*
     * Listing of article
     */
    function index()
    {
        $data['article'] = $this->Article_model->get_all_article();
        $this->load->view('templates/header');
        $data['_view'] = 'article/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new article
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'judul' => $this->input->post('judul'),
				'paragraph1' => $this->input->post('paragraph1'),
				'paragraph2' => $this->input->post('paragraph2'),
				'photo' => $this->input->post('photo'),
				'video' => $this->input->post('video'),
				'tanggal' => $this->input->post('tanggal'),
            );
            
            $article_id = $this->Article_model->add_article($params);
            redirect('article/index');
        }
        else
        {            
            $data['_view'] = 'article/add';
            $this->load->view('templates/header');
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a article
     */
    function edit($id)
    {   
        // check if the article exists before trying to edit it
        $data['article'] = $this->Article_model->get_article($id);
        
        if(isset($data['article']['id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'judul' => $this->input->post('judul'),
					'paragraph1' => $this->input->post('paragraph1'),
					'paragraph2' => $this->input->post('paragraph2'),
					'photo' => $this->input->post('photo'),
					'video' => $this->input->post('video'),
					'tanggal' => $this->input->post('tanggal'),
                );

                $this->Article_model->update_article($id,$params);            
                redirect('article/index');
            }
            else
            {
                $data['_view'] = 'article/edit';
                $this->load->view('templates/header');
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The article you are trying to edit does not exist.');
    } 

    /*
     * Deleting article
     */
    function remove($id)
    {
        $article = $this->Article_model->get_article($id);

        // check if the article exists before trying to delete it
        if(isset($article['id']))
        {
            $this->Article_model->delete_article($id);
            redirect('article/index');
        }
        else
            show_error('The article you are trying to delete does not exist.');
    }
    
}
