<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Comment_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get comment by commentid
     */
    function get_comment($commentid)
    {
        return $this->db->get_where('comment',array('commentid'=>$commentid))->row_array();
    }
        
    /*
     * Get all comment
     */
    function get_all_comment()
    {
        $this->db->order_by('commentid', 'desc');
        return $this->db->get('comment')->result_array();
    }
        
    /*
     * function to add new comment
     */
    function add_comment($params)
    {
        $this->db->insert('comment',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update comment
     */
    function update_comment($commentid,$params)
    {
        $this->db->where('commentid',$commentid);
        return $this->db->update('comment',$params);
    }
    
    /*
     * function to delete comment
     */
    function delete_comment($commentid)
    {
        return $this->db->delete('comment',array('commentid'=>$commentid));
    }
}
